### ISSUE TITLE
Default server does not start due to policy problem

### ISSUE THREAD

**Issue by a-schild** [ggrandes/sftpserver#13]
Starting the default server with default config aborts the server with this error:

```
2017-10-17 18:59:02,061 INFO org.javastack.sftpserver.Server Starting
2017-10-17 18:59:02,062 INFO org.javastack.sftpserver.Server Config file loaded 6 lines
2017-10-17 18:59:02,269 INFO org.apache.sshd.common.util.SecurityUtils Trying to register BouncyCastle as a JCE provider
2017-10-17 18:59:02,391 INFO org.apache.sshd.common.util.SecurityUtils Registration succeeded
2017-10-17 18:59:02,434 INFO org.javastack.sftpserver.Server SSHD SSHD-CORE-1.2.0
2017-10-17 18:59:02,447 INFO org.javastack.sftpserver.Server Listen on port=22222
2017-10-17 18:59:02,454 ERROR org.javastack.sftpserver.Server Exception java.security.AccessControlException: access denied ("java.util.PropertyPermission" "*" "read,write")
java.security.AccessControlException: access denied ("java.util.PropertyPermission" "*" "read,write")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkPropertiesAccess(SecurityManager.java:1262)
        at java.lang.System.getProperties(System.java:630)
        at org.apache.sshd.common.SyspropsMapWrapper.keySet(SyspropsMapWrapper.java:137)
        at org.apache.sshd.common.SyspropsMapWrapper.isEmpty(SyspropsMapWrapper.java:132)
        at org.apache.sshd.common.util.GenericUtils.isEmpty(GenericUtils.java:233)
        at org.apache.sshd.common.PropertyResolverUtils.resolvePropertyValue(PropertyResolverUtils.java:315)
        at org.apache.sshd.common.PropertyResolverUtils.getIntProperty(PropertyResolverUtils.java:148)
        at org.apache.sshd.common.io.AbstractIoServiceFactory.getNioWorkers(AbstractIoServiceFactory.java:84)
        at org.apache.sshd.common.io.nio2.Nio2ServiceFactory.<init>(Nio2ServiceFactory.java:42)
        at org.apache.sshd.common.io.nio2.Nio2ServiceFactoryFactory.create(Nio2ServiceFactoryFactory.java:54)
        at org.apache.sshd.common.io.DefaultIoServiceFactoryFactory.create(DefaultIoServiceFactoryFactory.java:49)
        at org.apache.sshd.common.helpers.AbstractFactoryManager.getIoServiceFactory(AbstractFactoryManager.java:101)
        at org.apache.sshd.server.SshServer.createAcceptor(SshServer.java:401)
        at org.apache.sshd.server.SshServer.start(SshServer.java:301)
        at org.javastack.sftpserver.Server.start(Server.java:245)
        at org.javastack.sftpserver.Server.main(Server.java:89)

```

Adding this line to lib/sftpd.policy solves the problem
`permission java.util.PropertyPermission "*", "read,write";
`

**Comment by ggrandes** [comment]
issue introduced in sshd-core 1.2.0
